name: paipfood_package
description: A new Flutter package project.
version: 0.0.1
publish_to: "none"
# homepage: paipfood_package

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  hive: ^2.2.3
  intl: ^0.18.1
  mask_text_input_formatter: ^2.4.0
  toastification: ^1.2.0
  logger: ^1.4.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  flutter_animate: ^4.2.0
  dio: ^5.1.2
  flutter_modular: ^5.0.3
  supabase_flutter: ^1.10.9
  window_manager: ^0.3.6
  pin_code_fields: ^8.0.1
  universal_io: ^2.2.2
  socket_io_client: ^2.0.3+1
  collection: ^1.18.0
  uuid: ^4.2.1
  dotted_border: ^2.1.0
  cropperx: ^1.1.1
  file_picker: ^6.1.1
  cached_network_image: ^3.3.1
  path_provider: ^2.1.2

  url_launcher: ^6.2.3
  sliver_tools: ^0.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - lib/fonts/
    - assets/
    - assets/flags/
    - assets/payments/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: icomoon
      fonts:
        - asset: lib/fonts/icomoon.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
